# fly.toml app configuration file generated for runteq-love-back on 2024-07-31T17:54:42+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'runteq-love-back'
primary_region = 'nrt'
console_command = '/rails/bin/rails console'

[build]
  dockerfile = './Dockerfile'

[deploy]
  release_command = './bin/rails db:prepare'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'

[[statics]]
  guest_path = '/rails/public'
  url_prefix = '/'
